### ISSUE TITLE
Is this coming back

### ISSUE THREAD

**Issue by Cheesegriller** [MatthewScholefield/port-craft#4]
I want to know

**Comment by MatthewScholefield** [comment]
Hmm, so I'm honestly not that interested in the computer version anymore so probably not. I am, however, still interested in the NDS version so I miiiight eventually release a rewritten version of [Mine DS](https://github.com/matthewScholefield/mine-ds) with more features.

**Comment by Cheesegriller** [comment]
> Hmm, so I'm honestly not that interested in the computer version anymore so probably not. I am, however, still interested in the NDS version so I miiiight eventually release a rewritten version of [Mine DS](https://github.com/matthewScholefield/mine-ds) with more features.

Holy crap
